name: Build and deploy application
run-name: ${{ github.actor }} is building and deploying application 🚀
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install node packages
        run : pnpm install --frozen-lockfile
        shell: bash

      - name: Build application
        run : pnpm run build
        shell: bash

      - name: Setup git user for deployment
        run : |
          git config user.name 'GitHub deployer'
          git config user.email 'LukasKez@users.noreply.github.com'
        shell: bash

      - name: Deploy application to GitHub Pages
        run : pnpm run deploy -u ${{ secrets.GITHUB_TOKEN }}
        shell: bash