name: Build and deploy application
run-name: ${{ github.actor }} is building and deploying application 🚀
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run : pnpm i
        shell: bash
      - run : pnpm ci
        shell: bash
      - run : pnpm run build
        shell: bash
      - run : pnpm run deploy
        shell: bash